### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by gdmcbain** [Data-Only-Greater/convergence#6]
I see 

https://github.com/Data-Only-Greater/convergence/blob/1407b0076ab2824c1e875c87c1d905af764d8f9f/setup.py#L23

and am wondering what's needed to be done to enable use under Python 3.9.

I'm working on a branch in which this restriction has been lifted (so that `pip install .` works), so I guess I'll find out.

**Comment by gdmcbain** [comment]
There's one error from `python -m doctest -v README.md`:
```
File "README.md", line 207, in README.md
Failed example:
    convergence[0] # doctest:+ELLIPSIS
Expected:
    Namespace(asymptotic_ratio=0.997980422462648, ...
Got:
    Namespace(grids='1 2 3', sizes=[1.0, 2.0, 4.0], values=[0.9705, 0.96854, 0.96178], fine=Namespace(r21=2.0, r32=2.0, e_approx=0.0020195775373519553, e_extrap=0.0008239813226325151, f_exact=0.9713003333333334, gci_coarse=0.0035552979563800613, gci_fine=0.0010308260346901172, p=1.7861695921669198, e_analytic=0.000823638422732444, f_analytic=0.9713, f_delta=-3.33333333379926e-07), coarse=Namespace(r21=2.0, r32=2.0, e_approx=0.0069795775084147155, e_extrap=0.002841894765814084, f_exact=0.9713003333333334, gci_coarse=0.012286964572105267, gci_fine=0.0035624926865868733, p=1.7861695921669198, e_analytic=0.002841552558426949, f_analytic=0.9713, f_delta=-3.33333333379926e-07), asymptotic_ratio=0.997980422462648)
```

**Comment by gdmcbain** [comment]
`pytest -n auto tests` passes O. K.

**Comment by gdmcbain** [comment]
So is it just that [Namespace](https://docs.python.org/3/library/argparse.html?highlight=argparse#argparse.Namespace) no longer alphabetizes its keys?

Possible remedy: skip this doctest?

https://github.com/Data-Only-Greater/convergence/commit/9103d9e1478022e121e89a4929479bba5f63fce3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R207

The value of `convergence[0].asymptotic_ratio` is tested immediately afterwards, so any failure should be caught right away.

**Comment by gdmcbain** [comment]
&hellip;or advance the ellipsis as in 91e2d09.

**Comment by H0R5E** [comment]
> …or advance the ellipsis as in [91e2d09](https://github.com/Data-Only-Greater/convergence/commit/91e2d09d385f5a9a24ac2a7c55a1a0c5518a4de5).

Thanks for reporting this. I've used the fix you suggested here. The PyPi release is now up to date as well.

**Comment by gdmcbain** [comment]
Thank you.
